
services:
  db:
    image: mysql:8.0
    container_name: sports-db
    restart: always
    environment:
      MYSQL_DATABASE: leaguepro
      MYSQL_ROOT_PASSWORD: ROOT
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - sports-net

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: sports-backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/leaguepro
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ROOT
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - sports-net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: sports-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - sports-net

volumes:
  db_data:

networks:
  sports-net:
    driver: bridge
